# bundle exec jekyll serve --port 4001 --baseurl ''

title: Лоббизм в Госдуме
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Лоббизм в госдуме. Описание проекта
baseurl: /lobby # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
