# bundle exec jekyll serve --port 4001 --baseurl ''

title: Лоббисты в Госдуме
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  DUMABINGO.RU — рассказываем, какие депутаты служат не только народу
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dumabingo.ru" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  about:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
